import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import Marquee from "@/component/Maequee";
import Footer from "@/component/Footer";

const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ["latin" , "bengali"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${notoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div><Navbar/></div>
        <div><Marquee/></div>
        <div>
          {children}
        </div>
        <div><Footer/></div>
      </body>
    </html>
  );
}
