import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import Marquee from "@/component/Marquee";
import Footer from "@/component/Footer";

const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSerifBengali.className} h-full antialiased`}
    >
      <body className="flex min-h-full min-w-0 flex-col">
        <Navbar />
        <div><Marquee /></div>
        <div className="min-w-0 flex-1">
          {children}
        </div>
        <div><Footer /></div>
      </body>
    </html>
  );
}
